version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4jDB
    environment:
      - NEO4J_AUTH=neo4j/Admin1234
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    ports:
      - "127.0.0.2:7475:7474"
      - "127.0.0.2:7688:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs: